# ---------------------------------------------------------------------------------
# CloudFormation Stack: GuardDuty, Health Dashboard, and Root User Sign-In Alerts
#
# This stack creates:
#   - An SNS topic (encrypted with the AWS managed SNS key) for security notifications.
#   - Email and SMS subscriptions to the SNS topic, with addresses provided as parameters.
#   - EventBridge rules that:
#       * Forward all GuardDuty findings to the SNS topic.
#       * Forward all AWS Health Dashboard events to the SNS topic.
#       * Forward all root user sign-in events (via CloudTrail) to the SNS topic.
#
# Deployment:
#   - Deploy as a StackSet to all accounts and regions you want to monitor.
#   - When deploying, specify the notification email and phone number.
#   - After deployment, confirm the SNS subscription(s) to start receiving alerts.
#
# Use Cases:
#   - Organization-wide security alerting for GuardDuty, Health, and root sign-ins.
#   - Centralized notification for security and operations teams.

# The SNS topic is encrypted with the AWS managed SNS key (alias/aws/sns).
# ---------------------------------------------------------------------------------

AWSTemplateFormatVersion: '2010-09-09'
Description: >
  EventBridge rules and SNS topic for GuardDuty, AWS Health Dashboard, and root user sign-in notifications in all organization accounts.
  Region is parameterized for documentation only.

Parameters:
  Region:
    Type: String
    Description: The AWS region where this stack is deployed (for documentation only).
    Default: us-west-2

  NotificationEmail:
    Type: String
    Description: Email address to receive notifications.

  NotificationPhone:
    Type: String
    Description: Phone number (in E.164 format, e.g., +1234567890) to receive SMS notifications.

Resources:
  GuardDutyHealthSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub iv-edd-${AWS::AccountId}-guardduty-health-notifications-${AWS::Region}
      KmsMasterKeyId: alias/aws/sns

  GuardDutyHealthSNSSubscriptionEmail:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Ref NotificationEmail
      TopicArn: !Ref GuardDutyHealthSNSTopic

  GuardDutyHealthSNSSubscriptionSMS:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sms
      Endpoint: !Ref NotificationPhone
      TopicArn: !Ref GuardDutyHealthSNSTopic

  GuardDutyFindingRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub iv-edd-${AWS::AccountId}-GuardDutyFindingToSNS-${AWS::Region}
      Description: "Send all GuardDuty findings to SNS"
      EventPattern:
        source:
          - aws.guardduty
        detail-type:
          - GuardDuty Finding
      Targets:
        - Arn: !Ref GuardDutyHealthSNSTopic
          Id: GuardDutySNSTarget

  HealthDashboardRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub iv-edd-${AWS::AccountId}-HealthDashboardToSNS-${AWS::Region}
      Description: "Send all AWS Health Dashboard notifications to SNS"
      EventPattern:
        source:
          - aws.health
      Targets:
        - Arn: !Ref GuardDutyHealthSNSTopic
          Id: HealthSNSTarget

  RootUserSignInRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub iv-edd-${AWS::AccountId}-RootUserSignInToSNS-${AWS::Region}
      Description: "Send notification to SNS when root user signs in"
      EventPattern:
        source:
          - aws.signin
        detail-type:
          - AWS Console Sign In via CloudTrail
        detail:
          userIdentity:
            type:
              - Root
          eventName:
            - ConsoleLogin
      Targets:
        - Arn: !Ref GuardDutyHealthSNSTopic
          Id: RootUserSignInSNSTarget

  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref GuardDutyHealthSNSTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: "sns:Publish"
            Resource: !Ref GuardDutyHealthSNSTopic

Outputs:
  SNSTopicArn:
    Description: SNS topic ARN for notifications
    Value: !Ref GuardDutyHealthSNSTopic
  DeploymentRegion:
    Description: The region this stack is intended for (for documentation)
    Value: !Ref Region



