AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create a secret in AWS Secrets Manager'

Parameters:
  SecretName:
    Type: String
    Description: Name of the secret
    Default: my-application-secret

  SecretDescription:
    Type: String
    Description: Description of the secret
    Default: Secret for my application

Resources:
  ApplicationSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Ref SecretName
      Description: !Ref SecretDescription
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

Outputs:
  SecretARN:
    Description: ARN of the created secret
    Value: !Ref ApplicationSecret
  SecretName:
    Description: Name of the created secret
    Value: !Ref SecretName 