# Template version and overall description
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create GitHub token secrets in AWS Secrets Manager and SSM Parameter Store'

# Define the input parameters that can be customized during stack creation
Parameters:
  # Name of the secret to be created in AWS Secrets Manager
  SecretName:
    Type: String
    Description: Name of the secret
    Default: github-token-secret

  # Description field for the secret to provide context
  SecretDescription:
    Type: String
    Description: Description of the secret
    Default: GitHub Token for Authentication

  # GitHub Token parameter (you'll provide this when creating the stack)
  GitHubTokenValue:
    Type: String
    Description: Your GitHub Token value
    NoEcho: true  # This ensures the token is not displayed in logs or console

# Define the AWS resources to be created
Resources:
  # SSM Parameter to store the GitHub token securely
  GitHubTokenParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: 'GITHUB_TOKEN'
      Description: 'Secure parameter storing GitHub Token'
      Type: 'String'
      Value: !Ref GitHubTokenValue
      Tier: 'Standard'

  # AWS Secrets Manager secret resource for storing GitHub token
  GitHubTokenSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      # Use the parameter value for secret name
      Name: !Ref SecretName
      # Use the parameter value for secret description
      Description: !Ref SecretDescription
      # Define the secret value structure with direct reference
      SecretString: !Sub '{"github_token": "${GitHubTokenValue}"}'

# Define the stack outputs
Outputs:
  # Output the ARN (Amazon Resource Name) of the created secret
  SecretARN:
    Description: ARN of the created secret
    Value: !Ref GitHubTokenSecret
  
  # Output the name of the created secret
  SecretName:
    Description: Name of the created secret
    Value: !Ref SecretName

  # Output the name of the SSM Parameter (but not its value for security)
  SSMParameterName:
    Description: Name of the SSM Parameter created
    Value: !Ref GitHubTokenParameter