AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Enables SSM, collects inventory, updates SSM agent, schedules daily patch scans, and provides a manual patch install+reboot association for all EC2 instances with PatchGroup=All.

Resources:
  SSMInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  SSMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref SSMInstanceRole

  # Collect Inventory
  InventoryAssociation:
    Type: AWS::SSM::Association
    Properties:
      Name: AWS-GatherSoftwareInventory
      Targets:
        - Key: tag:PatchGroup
          Values:
            - All
      ScheduleExpression: cron(0 0 * * ? *) # Daily at midnight UTC
      ComplianceSeverity: MEDIUM

  # Update SSM Agent
  UpdateSSMAgentAssociation:
    Type: AWS::SSM::Association
    Properties:
      Name: AWS-UpdateSSMAgent
      AssociationName: DailyUpdateSSMAgent
      Targets:
        - Key: tag:PatchGroup
          Values:
            - All
      ScheduleExpression: cron(0 1 * * ? *) # Daily at 1 AM UTC
      ComplianceSeverity: MEDIUM

  # Daily Patch Scan
  DailyPatchScanAssociation:
    Type: AWS::SSM::Association
    Properties:
      Name: AWS-RunPatchBaseline
      AssociationName: DailyPatchScan
      Targets:
        - Key: tag:PatchGroup
          Values:
            - All
      ScheduleExpression: cron(0 2 * * ? *) # Daily at 2 AM UTC
      Parameters:
        Operation:
          - Scan
      ComplianceSeverity: HIGH

  # Manual Patch Install + Reboot (no schedule)
  ManualPatchInstallRebootAssociation:
    Type: AWS::SSM::Association
    Properties:
      Name: AWS-RunPatchBaseline
      AssociationName: ManualPatchInstallReboot
      Targets:
        - Key: tag:PatchGroup
          Values:
            - All
      Parameters:
        Operation:
          - Scan
        # RebootOption:
        #   - RebootIfNeeded
      ComplianceSeverity: HIGH

Outputs:
  SSMInstanceProfile:
    Description: Attach this instance profile to your EC2 instances to enable SSM.
    Value: !Ref SSMInstanceProfile

Comments:
  - It will enable SSM, collect inventory, update the SSM agent, schedule daily patch scans, and provide a manual patch install+reboot association for all EC2 instances with PatchGroup=All.
  - The template is designed to be used in a single account.
  - The template is designed to be used in a single region.
  - Need to manually change from Scan to Install in the ManualPatchInstallRebootAssociation, and then uncomment the RebootIfNeeded parameter for reboot.
  - Because if you create it with reboot option it will run the reboot immediately, and if you don't select it, the reboot will not run until you run the association again.

